op-migrate:
	go build -o ./bin/op-migrate ./cmd/op-migrate/main.go

rollover:
	go build -o ./bin/rollover ./cmd/rollover/main.go

withdrawals:
	go build -o ./bin/withdrawals ./cmd/withdrawals/main.go

test:
	go test ./...

.PHONY: op-migrate rollover withdrawals test
