{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DL Node storage rate  (1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(dl_node_accumulative_store{type=\"size\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "num registered (self report)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dl_node_registered)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DL Disperser success rate(1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "rate(dl_disperser_size_success_traffic[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DL Node request rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(dl_node_accumulative_number_request[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Num registered on contract",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dl_disperser_num_registered", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum without(mode) (avg without(cpu, instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) / 1000000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "( node_filesystem_size_bytes{device=\"/dev/nvme0n1p1\", mountpoint=\"/etc/hosts\"}  - node_filesystem_avail_bytes{device=\"/dev/nvme0n1p1\", mountpoint=\"/etc/hosts\"}) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}