{
 "title": "operator-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "EigenDA metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current unexpired (Byte)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "dl_node_accumulative_store{type=\"size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "acc number store",
   "type": "stat",
   "description": "It counts cummulative number of stored dispersal the local node has served since its beginning",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dl_node_accumulative_store{type=\"number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "acc size store (Byte)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dl_node_accumulative_store{type=\"size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Unexpired (#)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "dl_node_current_store{type=\"number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator node status",
   "type": "stat",
   "description": "It counts cummulative number of data storage in bytes which the local node has served since its beginning. (including expired data)",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dl_node_registered", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "number request rate / min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "rate(dl_node_accumulative_number_request[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Hardware metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum without(mode) (avg without(cpu) (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(mode) (avg without(cpu) (irate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (GB)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage GB",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} - node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\"}) / 1000000000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "disk usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} - node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\"}) / node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} * 100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network tx utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "network Rx utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}